compilers=ljopt
defaultCompiler=ljopt

supportsBinary=false
interpreted=true
supportsExecute=true
objdumper=
demangler=
postProcess=
needsMulti=false

compiler.ljopt.exe=/opt/ljopt/ljopt-ce.sh
compiler.ljopt.name=ljopt + z3
compiler.ljopt.semver=0.1.0
compiler.ljopt.interpreted=true
compiler.ljopt.supportsExecute=true
