name: Testing

on:
  push:
  pull_request:

jobs:
  testing:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Cache LuaJIT
        uses: actions/cache@v3
        id: luajit-cache
        with:
          # This path should be same as the path in Makefile,
          # where tarantool's LuaJIT repo stored.
          path: build
          key: ${{ runner.os }}-luajit-${{ hashFiles('lua_patches/*.patch') }}

      - name: Setup packages
        run: sudo apt install -y luarocks

      - name: Setup rocks
        run: make deps

      - name: Building
        run: make build

      - name: Testing
        env:
          LJOPT_ENABLE_INTERNAL_CHECKS: 1
          LJOPT_STRICT: 1
        run: |
          eval $(luarocks path)
          make test

      - name: Testing with code coverage
        env:
          LJOPT_ENABLE_INTERNAL_CHECKS: 1
          LJOPT_STRICT: 1
        run: |
          eval $(luarocks path)
          make coverage
